Bad Request: /caracteristicas/api/v1/caracteristicas/
Watching for file changes with StatReloader
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Bad Request: /caracteristicas/api/v1/caracteristicas/
Bad Request: /caracteristicas/api/v1/caracteristicas/
Watching for file changes with StatReloader
Bad Request: /caracteristicas/api/v1/caracteristicas/
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Bad Request: /caracteristicas/api/v1/caracteristicas/
Watching for file changes with StatReloader
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Bad Request: /caracteristicas/api/v1/caracteristicas/
/Users/joanat/Development/Tournement/caracteristicas/views.py changed, reloading.
Watching for file changes with StatReloader
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Bad Request: /caracteristicas/api/v1/caracteristicas/
Watching for file changes with StatReloader
Bad Request: /caracteristicas/api/v1/caracteristicas/
/Users/joanat/Development/Tournement/caracteristicas/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /caracteristicas/api/v1/caracteristicas/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /caracteristicas/api/v1/caracteristicas/
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Bad Request: /caracteristicas/api/v1/caracteristicas/
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Bad Request: /caracteristicas/api/v1/caracteristicas/
Bad Request: /caracteristicas/api/v1/caracteristicas/
Not Found: /tournament_logos/24004c5.jpg
/Users/joanat/Development/Tournement/caracteristicas/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/caracteristicas/models.py changed, reloading.
Watching for file changes with StatReloader
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Not Found: /favicon.ico
Not Found: /
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
Not Found: /favicon.ico
Not Found: /apple-touch-icon-precomposed.png
Not Found: /apple-touch-icon.png
Watching for file changes with StatReloader
Not Found: /favicon.ico
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Watching for file changes with StatReloader
Not Found: /Inscripcion/api/v1/inscripcion
Not Found: /Inscripcion/api/v1/inscripcion/
Not Found: /inscripciones/api/v1/inscripciones/
Not Found: /inscripciones/api/v1/inscripciones/
Not Found: /inscripciones/api/v1/inscripciones/
Not Found: /inscripciones/api/v1/inscripciones/
Not Found: /inscripciones/api/v1/inscripciones/
Not Found: /inscripciones/api/v1/inscripciones/
Not Found: /inscripciones/api/v1/inscripciones/
Not Found: /inscripciones/api/v1/inscripciones/
Not Found: /inscripciones/api/v1/inscripciones/
Not Found: /inscripciones/api/v1/inscripciones/
/Users/joanat/Development/Tournement/inscripcion/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/inscripcion/apps.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/inscripcion/apps.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /inscripcion/api/v1/inscripcion
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/inscripcion/api/v1/inscripcion/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Bad Request: /inscripcion/api/v1/inscripcion/
Bad Request: /inscripcion/api/v1/inscripcion/
Bad Request: /inscripcion/api/v1/inscripcion/
Bad Request: /inscripcion/api/v1/inscripcion/
/Users/joanat/Development/Tournement/inscripcion/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /
/Users/joanat/Development/Tournement/mesas/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/apps.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/apps.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/apps.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /api/v1/mesas/ejecutar_primera/
/Users/joanat/Development/Tournement/mesas/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /api/v1/mesas/ejecutar_primera/
Not Found: /api/v1/mesas/ejecutar_primera/
Internal Server Error: /mesas/api/v1/mesas/ejecutar_primera/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/mesas/views.py", line 22, in ejecutar_primera
    mesas_primera()
  File "/Users/joanat/Development/Tournement/mesas/utils.py", line 10, in mesas_primera
    parejas = list(Parejas.objects.all().order_by('numero_pareja'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1659, in order_by
    obj.query.add_ordering(*field_names)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 2210, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'numero_pareja' into field. Choices are: Club_pertenencia, Jugador1, Jugador2, Nombre_pareja, Numero_pareja, id, ranking
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /caracteristicas/api/v1/incripcion/
Internal Server Error: /mesas/api/v1/mesas/ejecutar_primera/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/mesas/views.py", line 22, in ejecutar_primera
    mesas_primera()
  File "/Users/joanat/Development/Tournement/mesas/utils.py", line 10, in mesas_primera
    parejas = list(Parejas.objects.all().order_by('numero_pareja'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1659, in order_by
    obj.query.add_ordering(*field_names)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 2210, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'numero_pareja' into field. Choices are: Club_pertenencia, Jugador1, Jugador2, Nombre_pareja, Numero_pareja, id, ranking
/Users/joanat/Development/Tournement/mesas/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/utils.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /mesas/api/v1/mesas/ejecutar_primera/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/mesas/views.py", line 22, in ejecutar_primera
    mesas_primera()
  File "/Users/joanat/Development/Tournement/mesas/utils.py", line 10, in mesas_primera
    parejas = list(Parejas.objects.all().order_by('pareja.id'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1659, in order_by
    obj.query.add_ordering(*field_names)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 2210, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'pareja.id' into field. Choices are: Club_pertenencia, Jugador1, Jugador2, Nombre_pareja, Numero_pareja, id, ranking
/Users/joanat/Development/Tournement/mesas/utils.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /inscrpcion/api/v1/isncripcion/
Not Found: /inscrpcion/api/v1/isncripcion/
Not Found: /inscrpcion/api/v1/inscripcion/
Not Found: /tournament_logos/Bamboo.jpg
Not Found: /tournament_logos/Bamboo.jpg
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Internal Server Error: /admin/mesas/mesa/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: mesas_mesa.nombre_pareja_uno

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/contrib/admin/options.py", line 2065, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: mesas_mesa.nombre_pareja_uno
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/utils.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /mesas/api/v1/mesas/ejecutar_primera/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/mesas/views.py", line 22, in ejecutar_primera
    mesas_primera()
  File "/Users/joanat/Development/Tournement/mesas/utils.py", line 25, in mesas_primera
    mesa.nombre_pareja_uno = parejas[0].nombre if parejas else None
                             ^^^^^^^^^^^^^^^^^
AttributeError: 'Parejas' object has no attribute 'nombre'
Not Found: /favicon.ico
Internal Server Error: /mesas/api/v1/mesas/ejecutar_primera/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/mesas/views.py", line 22, in ejecutar_primera
    mesas_primera()
  File "/Users/joanat/Development/Tournement/mesas/utils.py", line 25, in mesas_primera
    mesa.nombre_pareja_uno = parejas[0].nombre if parejas else None
                             ^^^^^^^^^^^^^^^^^
AttributeError: 'Parejas' object has no attribute 'nombre'
Internal Server Error: /mesas/api/v1/mesas/ejecutar_primera/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/mesas/views.py", line 22, in ejecutar_primera
    mesas_primera()
  File "/Users/joanat/Development/Tournement/mesas/utils.py", line 25, in mesas_primera
    mesa.nombre_pareja_uno = parejas[0].nombre if parejas else None
                             ^^^^^^^^^^^^^^^^^
AttributeError: 'Parejas' object has no attribute 'nombre'
Not Found: /mesas/api/v1/mesas_primera
Not Found: /mesas/api/v1/ejecutar_primera
Not Found: /mesas/api/v1/ejecutar_primera/
Not Found: /mesas/api/v1/ejecutar_primera/
Internal Server Error: /mesas/api/v1/mesas/ejecutar_primera/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/mesas/views.py", line 22, in ejecutar_primera
    mesas_primera()
  File "/Users/joanat/Development/Tournement/mesas/utils.py", line 25, in mesas_primera
    mesa.nombre_pareja_uno = parejas[0].nombre if parejas else None
                             ^^^^^^^^^^^^^^^^^
AttributeError: 'Parejas' object has no attribute 'nombre'
/Users/joanat/Development/Tournement/mesas/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/utils.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /mesas/api/v1/mesas/ejecutar_primera/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/mesas/views.py", line 22, in ejecutar_primera
    mesas_primera()
  File "/Users/joanat/Development/Tournement/mesas/utils.py", line 24, in mesas_primera
    mesa.nombre_pareja_uno = pareja_uno_obj.nombre if pareja_uno_obj else None
                             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Parejas' object has no attribute 'nombre'
/Users/joanat/Development/Tournement/mesas/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/utils.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /mesas/api/v1/ejecutar_primera/
Not Found: /mesas/api/v1/ejecutar_primera/
Not Found: /mesas/api/v1/mesas/ejecutar_primera/ 
Not Found: /favicon.ico
Not Found: /mesas/api/v1/mesas/ejecutar_primera/ 
Not Found: /mesas/api/v1/mesas/mesas/
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /mesas/api/v1/mesas/undefined/
Watching for file changes with StatReloader
Not Found: /mesas/api/v1/mesas/undefined/
Not Found: /mesas/api/v1/mesas/undefined/
Watching for file changes with StatReloader
Not Found: /mesas/api/v1/mesas/undefined/
Not Found: /mesas/api/v1/mesas/undefined/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /resultados/api/v1/resultados/
Bad Request: /resultados/api/v1/resultados/
Watching for file changes with StatReloader
Bad Request: /resultados/api/v1/resultados/
Bad Request: /resultados/api/v1/resultados/
Internal Server Error: /resultados/api/v1/resultados
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/resultados/api/v1/resultados/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Watching for file changes with StatReloader
Bad Request: /resultados/api/v1/resultados/
Bad Request: /resultados/api/v1/resultados/
/Users/joanat/Development/Tournement/resultados/utils.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /resultados/api/v1/resultados/
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /resultados/api/v1/resultados/
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /favicon.ico
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/apps.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/apps.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/mesas/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /delete/1
Not Found: /delete/12
Not Found: /delete/13
Not Found: /delete/14
Not Found: /resultados/v1/api/resultados/delete/12
Not Found: /resultados/api/v1/resultados/14/
Not Found: /resultados/api/v1/resultados/14/
Bad Request: /resultados/api/v1/resultados/
Bad Request: /resultados/api/v1/resultados/
Not Found: /resultados/api/v1/resultados/14/
Not Found: /resultados/api/v1/resultados/14/
Bad Request: /resultados/api/v1/resultados/
Not Found: /resultados/api/v1/resultados/14/
Not Found: /resultados/api/v1/resultados/14/
Watching for file changes with StatReloader
Not Found: /resultados/api/v1/resultados/12/
Not Found: /resultados/api/v1/resultados/12/
Not Found: /mesas/api/v1/mesas/undefined/
Not Found: /mesas/api/v1/mesas/undefined/
Not Found: /mesas/api/v1/mesas/undefined/
Not Found: /mesas/api/v1/mesas/undefined/
Not Found: /mesas/api/v1/mesas/undefined/
Not Found: /mesas/api/v1/mesas/undefined/
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/ranking/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/ranking/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /resultados/api/v1/resultados/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
ranking.models.Ranking.DoesNotExist: Ranking matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 31, in save
    super(Resultado, self).save(*args, **kwargs)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 41, in post_save_resultado
    actualizar_ranking(instance)
  File "/Users/joanat/Development/Tournement/ranking/utils.py", line 14, in actualizar_ranking
    ranking_pareja_uno, _ = Ranking.objects.get_or_create(Numero_pareja=resultado.n_pareja_uno)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 923, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 369, in __set__
    super().__set__(instance, value)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "15": "Ranking.Numero_pareja" must be a "Parejas" instance.
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Internal Server Error: /admin/resultados/resultado/19/delete/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
ranking.models.Ranking.DoesNotExist: Ranking matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/contrib/admin/options.py", line 2106, in delete_view
    return self._delete_view(request, object_id, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/contrib/admin/options.py", line 2142, in _delete_view
    self.delete_model(request, obj)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1233, in delete_model
    obj.delete()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1132, in delete
    return collector.delete()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/deletion.py", line 512, in delete
    signals.post_delete.send(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 52, in post_delete_resultado
    actualizar_ranking(instance)
  File "/Users/joanat/Development/Tournement/ranking/utils.py", line 15, in actualizar_ranking
    ranking_pareja_uno, _ = Ranking.objects.get_or_create(Numero_pareja=resultado.n_pareja_uno)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 923, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 369, in __set__
    super().__set__(instance, value)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "15": "Ranking.Numero_pareja" must be a "Parejas" instance.
Internal Server Error: /resultados/api/v1/resultados/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
ranking.models.Ranking.DoesNotExist: Ranking matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 31, in save
    super(Resultado, self).save(*args, **kwargs)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 41, in post_save_resultado
    actualizar_ranking(instance)
  File "/Users/joanat/Development/Tournement/ranking/utils.py", line 15, in actualizar_ranking
    ranking_pareja_uno, _ = Ranking.objects.get_or_create(Numero_pareja=resultado.n_pareja_uno)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 923, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 369, in __set__
    super().__set__(instance, value)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "15": "Ranking.Numero_pareja" must be a "Parejas" instance.
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /resultados/api/v1/resultados/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 31, in save
    super(Resultado, self).save(*args, **kwargs)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 41, in post_save_resultado
    actualizar_ranking(instance)
  File "/Users/joanat/Development/Tournement/ranking/utils.py", line 14, in actualizar_ranking
    pareja_uno_instance = Parejas.objects.get(id=resultado_id)
                                                 ^^^^^^^^^^^^
NameError: name 'resultado_id' is not defined
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /resultados/api/v1/resultados/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 31, in save
    super(Resultado, self).save(*args, **kwargs)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 41, in post_save_resultado
    actualizar_ranking(instance)
  File "/Users/joanat/Development/Tournement/ranking/utils.py", line 14, in actualizar_ranking
    pareja_uno_instance = Parejas.objects.get(numero=resultado.n_pareja_uno)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 623, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1415, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1225, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'numero' into field. Choices are: Club_pertenencia, Jugador1, Jugador2, Nombre_pareja, Numero_pareja, SerieB, id, ranking
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /resultados/api/v1/resultados/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 31, in save
    super(Resultado, self).save(*args, **kwargs)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 41, in post_save_resultado
    actualizar_ranking(instance)
  File "/Users/joanat/Development/Tournement/ranking/utils.py", line 14, in actualizar_ranking
    pareja_uno_instance = Parejas.objects.get(Numero_pareja=resultado.n_pareja_uno)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
inscripcion.models.Parejas.DoesNotExist: Parejas matching query does not exist.
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /resultados/api/v1/resultados/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
ranking.models.Ranking.DoesNotExist: Ranking matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 31, in save
    super(Resultado, self).save(*args, **kwargs)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 41, in post_save_resultado
    actualizar_ranking(instance)
  File "/Users/joanat/Development/Tournement/ranking/utils.py", line 20, in actualizar_ranking
    ranking_pareja_uno, _ = Ranking.objects.get_or_create(Numero_pareja=resultado.n_pareja_uno)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 923, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/query.py", line 656, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 369, in __set__
    super().__set__(instance, value)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "15": "Ranking.Numero_pareja" must be a "Parejas" instance.
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /resultados/api/v1/resultados/17/
Not Found: /resultados/api/v1/resultados/17/
Not Found: /resultados/api/v1/resultados/28/
Not Found: /resultados/api/v1/resultados/28/
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /resultados/api/v1/resultados/26/
Not Found: /resultados/api/v1/resultados/26/
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /resultados/api/v1/resultados/29/
Not Found: /resultados/api/v1/resultados/29/
Not Found: /resultados/api/v1/resultados/18/
Not Found: /resultados/api/v1/resultados/18/
Watching for file changes with StatReloader
Not Found: /resultados/api/v1/resultados/35/
Not Found: /resultados/api/v1/resultados/35/
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /resultados/api/v1/resultados/36/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1132, in delete
    return collector.delete()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/deletion.py", line 512, in delete
    signals.post_delete.send(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 73, in post_delete_resultado
    Ranking.objects.filter(Numero_pareja=instance.n_pareja_uno).delete()
    ^^^^^^^
NameError: name 'Ranking' is not defined
Not Found: /resultados/api/v1/resultados/36/
Not Found: /resultados/api/v1/resultados/36/
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/ranking/utils.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /resultados/api/v1/resultados/37/
Not Found: /resultados/api/v1/resultados/37/
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /resultados/api/v1/resultados/38/
Not Found: /resultados/api/v1/resultados/38/
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /resultados/api/v1/resultados/39/
Not Found: /resultados/api/v1/resultados/39/
Internal Server Error: /resultados/api/v1/resultados/40/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1132, in delete
    return collector.delete()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/deletion.py", line 512, in delete
    signals.post_delete.send(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 70, in post_delete_resultado
    Ranking.objects.filter(Numero_pareja=instance.n_pareja_uno).delete()
    ^^^^^^^
NameError: name 'Ranking' is not defined
Internal Server Error: /resultados/api/v1/resultados/40/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1132, in delete
    return collector.delete()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/deletion.py", line 512, in delete
    signals.post_delete.send(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 70, in post_delete_resultado
    Ranking.objects.filter(Numero_pareja=instance.n_pareja_uno).delete()
    ^^^^^^^
NameError: name 'Ranking' is not defined
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /resultados/api/v1/resultados/40/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1132, in delete
    return collector.delete()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/deletion.py", line 512, in delete
    signals.post_delete.send(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 71, in post_delete_resultado
    Ranking.objects.filter(Numero_pareja=instance.n_pareja_uno).delete()
    ^^^^^^^
NameError: name 'Ranking' is not defined
Internal Server Error: /resultados/api/v1/resultados/40/
Traceback (most recent call last):
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1132, in delete
    return collector.delete()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/db/models/deletion.py", line 512, in delete
    signals.post_delete.send(
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/joanat/Development/Tournement/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joanat/Development/Tournement/resultados/models.py", line 71, in post_delete_resultado
    Ranking.objects.filter(Numero_pareja=instance.n_pareja_uno).delete()
    ^^^^^^^
NameError: name 'Ranking' is not defined
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/joanat/Development/Tournement/resultados/models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /resultados/api/v1/resultados/40/
Not Found: /resultados/api/v1/resultados/40/
Not Found: /resultados/api/v1/resultados/40/
Not Found: /resultados/api/v1/resultados/40/
